# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Directorio de la webpart a generar'
        # Default value if no value is explicitly provided
        default: 'C1-VentanasEmergentes'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest #windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.event.inputs.name }} 
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 10.x # optional
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true # optional 
      - run: npm i
      - run: rm -rf ./node_modules/@microsoft/gulp-core-build-typescript/node_modules/typescript
      - run: gulp clean
      - run: gulp bundle --ship
      - run: gulp package-solution --ship   
        env:
          CI: true
      - name: Output working directory
        run: pwd
      - name: Output directory structure
        run: ls sharepoint/solution/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          # Artifact name
          name: ${{ github.event.inputs.name }} # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.event.inputs.name }}/sharepoint/solution/*.sppkg
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: warn # optional, default is warn
      - run: pwd 
      - name: Notify build success
        run: echo "Se generó el artefacto para la webpart ${{ github.event.inputs.name }}"
